### ISSUE TITLE
Reporte Practica Hilos

### ISSUE THREAD

**Issue by CxrlosMX** [SistemasTecTlaxiaco/practica-de-hilos-CxrlosMX#2]
[Practica Hilos.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-hilos-CxrlosMX/files/6496355/Practica.Hilos.pdf)

**Comment by Anthony4523** [comment]
Calificación: 20

Calificó: Antonio González Hernández

**Comment by josealfredo79** [comment]
Bien hecho y revisado
